export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const OPEN_CART = "CART_OPEN"
export const CLOSE_CART = "CLOSE_CART"
export const SET_PRODUCTS = "SET_PRODUCTS"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
